import os

try:
    from importlib.metadata import version as get_version
except ImportError:
    from importlib_metadata import version as get_version

# -- General configuration ------------------------------------------------

# The extension modules to enable.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.doctest",
    "sphinx.ext.intersphinx",
    "sphinx.ext.coverage",
    "sphinx.ext.viewcode",
]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "Resolwe SDK for Python"
version = get_version("resdk")
release = version
author = "Genialis, Inc"
copyright = "2015-2026, " + author

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ["CHANGELOG.rst"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# -- Options for HTML output ----------------------------------------------

# The HTML theme, selectable per environment.
html_theme = os.environ.get("SPHINX_HTML_THEME") or "sphinx_nefertiti"

DOCS_HOST = os.environ.get("DOCS_HOST", "docs.genialis.com")
GOOGLE_ANALYTICS_ID = os.environ.get("GOOGLE_ANALYTICS_ID", "")

html_theme_options = {
    "project_short": project,
    "logo_url": f"https://{DOCS_HOST}/",
    "style_header_neutral": True,
    "style": "yellow",

    "header_links": [
        {
            "text": project,
            "link": f"https://{DOCS_HOST}/resdk/index.html",
        },
    ],
}

# The analytics option is theme-specific.
if GOOGLE_ANALYTICS_ID:
    html_theme_options["google_analytics_id"] = GOOGLE_ANALYTICS_ID

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}
